import { ArrowFatUp, Command } from "@phosphor-icons/react";

export const Keys = {
  MAC_COMMAND: <Command weight="bold" />,
  MAC_OPTION: "⌥",
  MAC_CONTROL: "⌃",
  SHIFT: <ArrowFatUp weight="bold" />,
  ENTER: "⏎",
  DELETE: "⌫",
  TAB: "⇥",
  SPACE: "␣",
  ARROW_UP: "↑",
  ARROW_DOWN: "↓",
  ARROW_LEFT: "←",
  ARROW_RIGHT: "→",
  PAGE_UP: "⇞",
  PAGE_DOWN: "⇟",
  HOME: "↖",
  END: "↘",
  BACKSPACE: "⌫",
  CAPS_LOCK: "⇪",
  PRINT_SCREEN: "PrtSc",
  SCROLL_LOCK: "⇳",
  PAUSE_BREAK: "Pause",
  INSERT: "Ins",
  NUM_LOCK: "Num",
  CONTEXT_MENU: "Menu",
  WINDOWS: "⊞",
  ALT: "Alt",
  CONTROL: "Ctrl",
} as const;
